import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={cn('dark relative h-full font-sans antialiased', inter.className)}>
        <Navbar />
        <main className="container mx-auto flex flex-col min-h-screen relative">
          {children}
        </main>
      </body>
    </html>
  )
}
